### ISSUE TITLE
Mancano i commenti

### ISSUE THREAD

**Issue by iannellog** [davidepietrangeli/Battaglianavale#1]
Mancano quasi completamente i commenti relativi alle classi e quelli che ci sono non sono di aiuto.
Devi inserire commenti sufficienti a risostruire la logica del programma.
In particolare per ogni metodo si deve capire chiaramente con riferimento al problema in esame (la battaglia navale):
- cosa fa
- che ruolo hanno i parametri
- cosa viene restituito
Senza commenti adeguati non posso valutare il codice.

**Comment by davidepietrangeli** [comment]
Fatto
