### ISSUE TITLE
Sollevare un'eccezione

### ISSUE THREAD

**Issue by supix** [davidepietrangeli/Battaglianavale#15]
https://github.com/davidepietrangeli/Battaglianavale/blob/738b3c48097576d124eea4056ab1dec1fa4d2b42/inputs.py#L70

Perché l'eccezione non è stata sollevata con la sintassi consueta?

```raise ValueError('\u001b[31mNumero non valido diInvalid number of rows\033[0m')```

**Comment by davidepietrangeli** [comment]
Avevo utilizzato una sintassi diversa perché ignoravo la corretta sintassi.
Ho applicato delle modifiche, spero di aver modificato correttamente il tutto.
