### ISSUE TITLE
Uso di enumerazioni

### ISSUE THREAD

**Issue by supix** [davidepietrangeli/Battaglianavale#16]
https://github.com/davidepietrangeli/Battaglianavale/blob/738b3c48097576d124eea4056ab1dec1fa4d2b42/utile.py#L60

Lo stato di una cella del campo di battaglia può assumere uno tra N valori. E' stato scelto di rappresentarlo con dei caratteri.
Un'altra possibilità sarebbe potuta essere quella di utilizzare delle enumerazioni, come indicato [a questo link](https://docs.python.org/3/library/enum.html).

I vantaggi nell'uso di un'enum sono i seguenti:

* correttezza: non è possibile rappresentare un valore inesistente;
* leggibilità: il valore di un'enum ha un significato di immediata comprensione.

**Comment by davidepietrangeli** [comment]
fatto

**Comment by supix** [comment]
La stessa modifica andrebbe applicata anche agli altri stati di una cella del campo. Come per es.:

https://github.com/davidepietrangeli/Battaglianavale/blob/25bd3897250efb772746c5a514a25dfd99dea9b5/campo.py#L110

https://github.com/davidepietrangeli/Battaglianavale/blob/25bd3897250efb772746c5a514a25dfd99dea9b5/campo.py#L117

Che significa `== 1`? Con un'enum il significato sarebbe evidente.

**Comment by davidepietrangeli** [comment]
Fatto prof, ho introdotto :
class Campo(Enum):
    VUOTO = '-'
    NAVE = '1'
cosi dove c'è la nave che c'è il numero 1 ho sostituito l'enumerazione.
