### ISSUE TITLE
Classe Campo: attributo `navi`

### ISSUE THREAD

**Issue by iannellog** [davidepietrangeli/Battaglianavale#2]
Non si capisce quando viene inizializzato l'attributo `navi`. 
Di fatto sembra che sia sempre una lista vuota.
Il problema è collegato al metodo `posiziona_navi`la cui funzione non è chiara.
Maggiore attenzione anche a come si scelgono i nomi. 
Per es. il metodo `aggiorna_campo` chiaramente non *aggiorna* nulla, ma emttette sullo standard output la matrice di caratteri riferita dall'attributo `campo`.

**Comment by davidepietrangeli** [comment]
Nel file 'battaglianavale.py' richiamo il metodo 'crea_nave_tipo_lista' nel file 'utile.py' mi creo la lista delle navi 'tipo_lista'. 
Successivamente, sempre nel file 'battaglianavale.py' richiamo il metodo 'crea_campo' passandogli 'tipo_lista' per assegnare una posizione nel campo di gioco di ogni nave per ogni giocatore.

**Comment by iannellog** [comment]
C'è un problema nella gestione dell'attribito `coordinate`della classe `Nave`.
L'attuale codice consente di creare una nave con l'attributo `coordiante` uguale a una lista vuota. In tal caso non sarebbe possibile chiamare i metodi `nave_colpita` o `colpo` perché restituirebbero sempre False.
Questo non va bene.
Poiché di fatto le navi vengono sempre create passandogli delle coordinate non vuote (vedi file campo.py) il problema si risolve eliminando il valore di default dal parametro `coordinate` del costruttore ed eliminando le righe 13-16.

**Comment by davidepietrangeli** [comment]
Fatto

**Comment by iannellog** [comment]
Resta il valore default per il parametro `coordinate` del costruttore.

**Comment by davidepietrangeli** [comment]
per valore di default cosa intende? Io ho come parametro del costruttore della classe 'Nave':
self.coordinate = coordinate
Restituisco il valore della variabile 'coordinate' all'attributo self.coordinate.

**Comment by iannellog** [comment]
Nell'interfaccia del costruttore (riga 4) c'è il parametro con valore di default:

> coordinate=None

Questo vuol dire che posso creare un oggetto della classe `Nave` SENZA passargli il parametro `coordinate`. 
Questo a sua volta vuol dire che creo un oggetto incosistente (per il quale, per esempio, non ha senso applicare altri metodi).

In altre parole devi togliere il valore di default in modo che sia obbligatorio passare il parametro `coordinate`.

**Comment by davidepietrangeli** [comment]
fatto
