### ISSUE TITLE
Introdurre funzioni

### ISSUE THREAD

**Issue by iannellog** [davidepietrangeli/Battaglianavale#4]
Si può migliorare e rendere più leggibile il codice introducento delle funzioni al posto di ripetere segmenti di codice molto simili.
Ad esempio nel file `battaglianavale.py` i segmenti corrispondenti alle righe 39-80 e 85-126 sono praticamente identici a meno del giocatore a cui si riferiscono. 
Introdurre una funzione identificando quali sono i parametri in modo da scrivere il codice una sola volta e rendere più leggibile il tutto (ovviamente con i dovuti commenti).
Verificare se la stessa cosa è opportuna in altri punti del programma.

**Comment by davidepietrangeli** [comment]
Ho reso il file battaglianavale.py sintetico rimuovendo i segmenti corrispondenti alle righe 39-80 e 85-126. Il metodo del posizionamento delle navi l'ho implementato nel file 'campo.py' all'interno del metodo 'crea_campo'.

**Comment by iannellog** [comment]
Nel commento alla funzione (non è un metodo) `crea_campo` manca l'informazione sui parametri di ingresso e su cosa ritorna (quest'ultima cosa particolarmente importante in quanto l'interfaccia non la specifica). 

Stesso discorso per le funzioni `controllo_posizionamento_orizzontale_nave` e `controllo_posizionamento_verticale_nave`.

**Comment by davidepietrangeli** [comment]
Fatto
