### ISSUE TITLE
Semplificare le madalità di input dei dati

### ISSUE THREAD

**Issue by iannellog** [davidepietrangeli/Battaglianavale#6]
Attualmente per ogni vave occorre digitare separatamente riga, colonna e orientamento, quest'ultimo digitando l'intera parola.

Questo rende molto fastidiosa la fase di inizializzazione.

Semplificare:
- la posizione può essere inserita dando righa e colonna insieme separati da uno spazio (per es: 2 3)
- l'orientamento può essere dato indicando solo la lettera iniziale (indifferentemente se maiuscola o minuscola)

Inoltre attualmente se sbaglio a scrivere l'orientamento devo re-immettere anche la posizione, correggere in modo che si deba re-immettere solo l'ultima informazione errata.

**Comment by davidepietrangeli** [comment]
La posizione non può essere inserita dando riga e colonna insieme separati da uno spazio per una scelta progettuale personale, in quanto:
- a seconda della riga di partenza e della colonna di partenza vengono svolte delle azioni di controllo sul posizionamento della nave ( ad esempio se è adiacente ad un'altra).
-  inoltre, concettualmente se entrambi gli indici sono numerici è corretto che i due input siano separati per evitare confusioni.
Per quanto riguarda l'orientamento, comprendo la sua issue e ho proceduto alla modifica. 
Ora per decidere l'orientamento basta inserire 'v' oppure 'o'.
Errore mi riporta ad inserire di nuovo le coordinate in quanto se la nave fosse adiacente o in una posizione sbagliata non basta reinserire solo l'orientamento ma anche le coordinate.
Viene stampato un errore se si introduce un intero non valido per la riga e per la colonna altrimenti si continua all'inserimento dell'orientamento. E' logico che se la nave in quelle coordinate e con quell'orientamento ad esempio sia adiacente ad un'altra e debba essere riposizionata, non venga chiesto solo l'orientamento ma anche delle nuove coordinate.

**Comment by davidepietrangeli** [comment]
Ho assecondato la sua richiesta.
Ora per inserire la riga e la colonna dove posizionare la nave uso un singolo input.
Lo stesso per quanto riguarda la riga e la colonna dove sparare.
