### ISSUE TITLE
File giocatore.py

### ISSUE THREAD

**Issue by iannellog** [davidepietrangeli/Battaglianavale#7]
La logica implementata è molto difficile da ricostruire. Segnalo alcune cose che possono aiutare a migliorare, ma probabilmente non bastano. In generale occorre fare uno sforzo per chiarire meglio nei commenti quale è il ruolo delle varie funzioni:

- non si capisce a che serve il parametro di ingresso `fine_gioco` nella funzione ` cambio_giocatore`: di fatto viene sempre passato il valore False
- di conseguenza lo stesso parametro di ingresso è sempre False anche quando si chiama la funzione `sparo` e quindi anche per questa funzione non si capisce a che serve in ingresso (infatti il parametro non viene mai usato, ma solo definito)
- i commenti alle funzioni cercano (senza riuscirci del tutto) di spiegare il significato dei parametri di ingresso, ma non spiegano chiaramente COSA fanno
- un esempio di commento che non è chiaro è quello alla riga 65: 

     > 'colpo': variabile booleana che indica se è stato effettuato un colpo

  in realtà non indica se *è stato effettuato un colpo*, ma se *l'ultimo colpo effettuato è andato a segno o no* che è cosa diversa rispetto alla logica del codice
- l'informazione su ciò che viene restituito deve essere aggiunta al commento iniziale e non in fondo (vedi righe per es. righe 44 e 96)
- c'è una confusione tra il termine *funzione* e il termine *metodo*: i metodi sono funzioni interne a una classe e quindi in questo file ci sono funzioni, non metodi
- non sarebbe più logico (e leggibile) chiamare la funzione `vittoria` dopo il ciclo in ìnizio_gioco` piuttosto che nella funzione `sparo`?

**Comment by davidepietrangeli** [comment]
Se un giocatore affonda tutte le navi il parametro 'fine_gioco' viene inizializzato a True e dato alla funzione 'cambio_giocatore' permette la fine dell'alternarsi dei turni in quanto la partita è finita con la vittoria di quel giocatore.
Ho spostato il commento di cosa restituisce una funzione all'inizio di ogni funzione.
Ho commentato con 'funzione' tutto ciò che non era un 'metodo' ma una funzione.
Ho migliorato i commenti sperando siano diventati chiari.

**Comment by iannellog** [comment]
La prima affermazione della risposta è sbagliata.
La chiamata a `cambio_giocatore` è all'interno di un ciclo che ha come condizione di uscita:
> not fine_gioco

quindi quando viene chiamata la funzione il parametro in ingresso deve per forza essere sempre **False**.

Per evitare di controllare le altre navi nel caso ne sia già stata colpita una puoi inserire un `break` dopo la riga 35.
