### ISSUE TITLE
File campo 

### ISSUE THREAD

**Issue by iannellog** [davidepietrangeli/Battaglianavale#8]
Il codice delle funzioni `controllo_posizionamento_orizzontale_nave` e `controllo_posizionamento_verticale_nave` andrebbe commentato meglio:
- per esempio quale è il ruolo del ciclo while?
- i diversi if cosa controllano? (sarebbe meglio non chidere a chi legge il codice di ricostruire la logica seguita nello scrivere le varie condizioni)

Bisognerebbe anche chiarire che nella funzione `crea_campo` la matrice di numeri viene creata solo per verificare che le navi siano posizionate correttamente e non viene più usata successivamente. Pertanto è anche inutile restituirla al chiamante.

Un problema che resta mi pare è anche che non si controlla che la riga di un numero positivo e se si mettono numeri negativi succedono cose strane. Sulle colonne in un caso il programma è andato in errore.

**Comment by davidepietrangeli** [comment]
Indicato tutto nei commenti
La funzione 'crea_Campo' l'ho mantenuta così com'è e la restituisco al chiamante per poi darla in ingresso alle funzioni di controllo dell'orientamento che necessitano della posizione delle altri navi nel campo per verificare se si può mettere una nave in quella posizione.
Il problema che se si mettono numeri negativi succedono cose strane viene risolto con la comunicazione dell'errore e e al terzo errore dall'uscita del programma. Considerare nell'analisi dei requisiti che un utente possa mettere una riga o una colonna come intero negativo nonostante venisse segnalato il range di interi da inserire mi sembra paradossale.

**Comment by iannellog** [comment]
La mia osservazione su `crea_campo` non riguardava il fatto che la matrice veniva creata: è chiaro a cosa serve ALL'INTERNO di `crea_campo`.

Il punto è che non serve restituirla in uscita perché il chiamante poi non la usa più!

**Comment by davidepietrangeli** [comment]
ho corretto il problema da lei sollevato, ho eliminato la restituzione del parametro campo
